name: allure-python-test

on:
  push:
    branches-ignore:
      - '!master'
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        bucket:
          description: 'Bucket name in AWS S3 which contains the config.py, for example: rs-develop-config'
          required: true  

jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-latest
    steps:
        # Input Parameters
      - name: Setup variables for workflow dispatch
        run: |
          echo "bucket=${{ github.event.inputs.bucket }}" >> $GITHUB_ENV
        if: github.event_name == 'workflow_dispatch'

      - run: |
          echo "bucket: ${{ env.bucket }}"
    
      - uses: actions/checkout@v2
      
      - name: conditional command
        run: |
          echo "I am bucket: ${{ env.bucket }}"
          if ${{ env.bucket }} == "rs-develop"; then
              echo "bingo bucket: ${{ env.bucket }}"
          else
              echo "domage bucket: ${{ env.bucket }}"
          fi
