name: Non-Regression-Test on PR

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Playwright
        run: npm run test:install 

      - name: Setup environment variables
        run: |
          DATE=$(date -u -d 'today' +'%Y-%m-%d-%H-%M-%S')
          TARGET=${{github.event.number}}
          TOTAL=${{steps.nrt.outputs.total}}
          PASSED=${{steps.nrt.outputs.passed}}
          FAILED=${{steps.nrt.outputs.failed}}
          SKIPPED=${{steps.nrt.outputs.skipped}}
          DURATION="${{steps.nrt.outputs.duration}}"
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "REPORT=$DATE.$TARGET.$PASSED.$FAILED.$SKIPPED" >> $GITHUB_ENV
          echo "TOTAL=$TOTAL" >> $GITHUB_ENV
          echo "PASSED=$PASSED" >> $GITHUB_ENV
          echo "FAILED=$FAILED" >> $GITHUB_ENV
          echo "SKIPPED=$SKIPPED" >> $GITHUB_ENV
          echo "DURATION=$DURATION" >> $GITHUB_ENV
          if ${{ steps.nrt.outputs.success }}
          then
            echo "RESULT=Succeded :heavy_check_mark:" >> $GITHUB_ENV
          else
            echo "RESULT=Failed :x:" >> $GITHUB_ENV
          fi
